---
output: 
  md_document
---
# bmstdr: Bayesian Modeling of Spatio-Temporal Data with R 
## Author: <a href="https://www.sujitsahu.com/">Sujit K. Sahu </a>
### Date: "`r today <- Sys.Date(); format(today, format="%B %d,  %Y")`"
# Introduction: 

 This is a vignette for the `R` package `r BiocStyle::CRANpkg("bmstdr")`. The package facilitates Bayesian modeling of both point reference and areal unit data with or without temporal replications. Three main functions in the package: `Bspatial` for spatial only point referene data,   `Bsptime` for spatio-temporal point reference data  and `Bcartime` for  areal unit data,  which may also vary in time,  perform the main modeling and validation tasks. Computations and inference in a Bayesian modeling framework   are done using popular `R` software packages such as `r BiocStyle::CRANpkg("spBayes")`, `r BiocStyle::CRANpkg("spTimer")`,  `r BiocStyle::CRANpkg("spTDyn")`, `r BiocStyle::CRANpkg("CARBayes")`, `r BiocStyle::CRANpkg("CARBayesST")` and also code written using computing platforms  `r BiocStyle::Rpackage("INLA")` and `r BiocStyle::CRANpkg("rstan")`. 
 
 <p> 
 
  Point reference data are modeled using the Gaussian error distribution only but a top level  generalized linear model is used for areal data modeling. The user of `r BiocStyle::CRANpkg("bmstdr")` is afforded the flexibility to choose an appropriate package and is also free to name the rows of their input data frame for validation  purposes. The package  incorporates a range of prior distributions allowable in the nominated  packages with default hyperparameter values.   The package allows quick comparison of models using both model choice criteria,  such as DIC  and WAIC,  and facilitates K-fold cross-validation without much programming effort. Familiar diagnostic plots and model fit exploration using the S3 methods such as  `summary`, `residuals` and `plot` are included so that a beginner user  confident in model fitting using the base `R` function  `lm` can quickly learn to analyzing data by fitting  a range of appropriate spatial and spatio-temporal models.  This vignette illustrates the package using five built-in data sets.  Three of these are on point reference data on air pollution and temperature at the deep ocean and the other two are areal unit data sets on Covid-19 mortality in England. 