// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gibbs_cpp
NumericMatrix gibbs_cpp(int N, int thin);
RcppExport SEXP _bmstdr_gibbs_cpp(SEXP NSEXP, SEXP thinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_cpp(N, thin));
    return rcpp_result_gen;
END_RCPP
}
// crps_one
double crps_one(NumericVector p);
RcppExport SEXP _bmstdr_crps_one(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(crps_one(p));
    return rcpp_result_gen;
END_RCPP
}
// crpscpp
double crpscpp(NumericMatrix tmp);
RcppExport SEXP _bmstdr_crpscpp(SEXP tmpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tmp(tmpSEXP);
    rcpp_result_gen = Rcpp::wrap(crpscpp(tmp));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_stan_fit4gp_marginal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ind_gpp_marginal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4normal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4spatial_model_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_bmstdr_gibbs_cpp", (DL_FUNC) &_bmstdr_gibbs_cpp, 2},
    {"_bmstdr_crps_one", (DL_FUNC) &_bmstdr_crps_one, 1},
    {"_bmstdr_crpscpp", (DL_FUNC) &_bmstdr_crpscpp, 1},
    {"_rcpp_module_boot_stan_fit4gp_marginal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gp_marginal_mod, 0},
    {"_rcpp_module_boot_stan_fit4ind_gpp_marginal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ind_gpp_marginal_mod, 0},
    {"_rcpp_module_boot_stan_fit4normal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4normal_mod, 0},
    {"_rcpp_module_boot_stan_fit4spatial_model_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4spatial_model_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bmstdr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
