# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbs_cpp <- function(N, thin) {
    .Call('_bmstdr_gibbs_cpp', PACKAGE = 'bmstdr', N, thin)
}

crps_one <- function(p) {
    .Call('_bmstdr_crps_one', PACKAGE = 'bmstdr', p)
}

crpscpp <- function(tmp) {
    .Call('_bmstdr_crpscpp', PACKAGE = 'bmstdr', tmp)
}

